# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-12 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200412_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 13, 45, 27, 144381, tzinfo=utc), null=True),
        ),
    ]
